# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spaghettifiedcat/Documents/astroparticle/haloscope/geant4/first_actual_attempt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spaghettifiedcat/Documents/astroparticle/haloscope/geant4/first_actual_attempt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spaghettifiedcat/Documents/astroparticle/haloscope/geant4/first_actual_attempt/CMakeFiles /home/spaghettifiedcat/Documents/astroparticle/haloscope/geant4/first_actual_attempt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spaghettifiedcat/Documents/astroparticle/haloscope/geant4/first_actual_attempt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

#=============================================================================
# Target rules for targets named Simulation

# Build rule for target.
Simulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Simulation
.PHONY : Simulation

# fast build rule for target.
Simulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Simulation.dir/build.make CMakeFiles/Simulation.dir/build
.PHONY : Simulation/fast

ActionInitialization.o: ActionInitialization.cc.o
.PHONY : ActionInitialization.o

# target to build an object file
ActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ActionInitialization.cc.o
.PHONY : ActionInitialization.cc.o

ActionInitialization.i: ActionInitialization.cc.i
.PHONY : ActionInitialization.i

# target to preprocess a source file
ActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ActionInitialization.cc.i
.PHONY : ActionInitialization.cc.i

ActionInitialization.s: ActionInitialization.cc.s
.PHONY : ActionInitialization.s

# target to generate assembly for a file
ActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ActionInitialization.cc.s
.PHONY : ActionInitialization.cc.s

DetectorConstruction.o: DetectorConstruction.cc.o
.PHONY : DetectorConstruction.o

# target to build an object file
DetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/DetectorConstruction.cc.o
.PHONY : DetectorConstruction.cc.o

DetectorConstruction.i: DetectorConstruction.cc.i
.PHONY : DetectorConstruction.i

# target to preprocess a source file
DetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/DetectorConstruction.cc.i
.PHONY : DetectorConstruction.cc.i

DetectorConstruction.s: DetectorConstruction.cc.s
.PHONY : DetectorConstruction.s

# target to generate assembly for a file
DetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/DetectorConstruction.cc.s
.PHONY : DetectorConstruction.cc.s

ParticleMessenger.o: ParticleMessenger.cc.o
.PHONY : ParticleMessenger.o

# target to build an object file
ParticleMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ParticleMessenger.cc.o
.PHONY : ParticleMessenger.cc.o

ParticleMessenger.i: ParticleMessenger.cc.i
.PHONY : ParticleMessenger.i

# target to preprocess a source file
ParticleMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ParticleMessenger.cc.i
.PHONY : ParticleMessenger.cc.i

ParticleMessenger.s: ParticleMessenger.cc.s
.PHONY : ParticleMessenger.s

# target to generate assembly for a file
ParticleMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/ParticleMessenger.cc.s
.PHONY : ParticleMessenger.cc.s

PhysicsList.o: PhysicsList.cc.o
.PHONY : PhysicsList.o

# target to build an object file
PhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PhysicsList.cc.o
.PHONY : PhysicsList.cc.o

PhysicsList.i: PhysicsList.cc.i
.PHONY : PhysicsList.i

# target to preprocess a source file
PhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PhysicsList.cc.i
.PHONY : PhysicsList.cc.i

PhysicsList.s: PhysicsList.cc.s
.PHONY : PhysicsList.s

# target to generate assembly for a file
PhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PhysicsList.cc.s
.PHONY : PhysicsList.cc.s

PrimaryGeneratorAction.o: PrimaryGeneratorAction.cc.o
.PHONY : PrimaryGeneratorAction.o

# target to build an object file
PrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PrimaryGeneratorAction.cc.o
.PHONY : PrimaryGeneratorAction.cc.o

PrimaryGeneratorAction.i: PrimaryGeneratorAction.cc.i
.PHONY : PrimaryGeneratorAction.i

# target to preprocess a source file
PrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PrimaryGeneratorAction.cc.i
.PHONY : PrimaryGeneratorAction.cc.i

PrimaryGeneratorAction.s: PrimaryGeneratorAction.cc.s
.PHONY : PrimaryGeneratorAction.s

# target to generate assembly for a file
PrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/PrimaryGeneratorAction.cc.s
.PHONY : PrimaryGeneratorAction.cc.s

sim.o: sim.cc.o
.PHONY : sim.o

# target to build an object file
sim.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cc.o
.PHONY : sim.cc.o

sim.i: sim.cc.i
.PHONY : sim.i

# target to preprocess a source file
sim.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cc.i
.PHONY : sim.cc.i

sim.s: sim.cc.s
.PHONY : sim.s

# target to generate assembly for a file
sim.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/sim.cc.s
.PHONY : sim.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Simulation"
	@echo "... sim"
	@echo "... ActionInitialization.o"
	@echo "... ActionInitialization.i"
	@echo "... ActionInitialization.s"
	@echo "... DetectorConstruction.o"
	@echo "... DetectorConstruction.i"
	@echo "... DetectorConstruction.s"
	@echo "... ParticleMessenger.o"
	@echo "... ParticleMessenger.i"
	@echo "... ParticleMessenger.s"
	@echo "... PhysicsList.o"
	@echo "... PhysicsList.i"
	@echo "... PhysicsList.s"
	@echo "... PrimaryGeneratorAction.o"
	@echo "... PrimaryGeneratorAction.i"
	@echo "... PrimaryGeneratorAction.s"
	@echo "... sim.o"
	@echo "... sim.i"
	@echo "... sim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

